### ISSUE TITLE
Potential updates to filters.txt sources

### ISSUE THREAD

**Issue by KilometerM** [mmotti/adguard-home-filters#10]
Hello,

Thank you for your AG Home filter list. I think it's great. I'd like to suggest a few updates to the sources used, based on the information below. As it is your list, however, I respect whatever decision you make.

1. The disconnect lists should be considered for removal from the list. Disconnect.me has indicated that the lists are "[...]not maintained, has not been updated, and is not actively distributed us." As a result of this information, they have been removed from the pi-hole default lists and I feel they should be removed here too. See [https://github.com/pi-hole/pi-hole/issues/3450](https://github.com/pi-hole/pi-hole/issues/3450) for more information.
2. https://www.malwaredomainlist.com/hostslist/hosts.txt is redundant as it is already included in StevenBlack's unified hosts and could be considered for removal. This can be seen [here](https://github.com/StevenBlack/hosts/blob/master/readme.md#sources-of-hosts-data-unified-in-this-variant) in StevenBlack's readme under sources.

Thank you again for the great list.

**Comment by mmotti** [comment]
Hi :-) Thanks for you suggestions.

I have removed said lists from the list sources. Thanks for pointing these out! I haven't kept my eyes on them recently as I've just left this ticking over in the background.
