### ISSUE TITLE
Ubuntu update issue

### ISSUE THREAD

**Issue by bruvv** [mmotti/adguard-home-filters#11]
This rule:
`/^ad([sxv]?[0-9]*|system)[_.-]([^.[:space:]]+\`
Gives issues with the following domains that is needed when running a ubuntu server:
```
eu-frankfurt-1-ad-3.clouds.archive.ubuntu.com
_https._tcp.eu-frankfurt-1-ad-3.clouds.archive.ubuntu.com
```

**Comment by mmotti** [comment]
Hi,

This seems to be an unfortunate false positive.

I have added a rule to filters.txt (`@@||clouds.archive.ubuntu.com^`) which should prevent this.

Cheers for reporting!
