### ISSUE TITLE
couple of false positives

### ISSUE THREAD

**Issue by slalik** [mmotti/adguard-home-filters#13]
1. intel.com and all its subdomains are blocked. This comes from the ads-and-tracking-extended.txt list.

2. track24.ru and track24.net blocked by regexps. These are postal services trackers.

**Comment by mmotti** [comment]
Hey!

Thanks for reporting.

I have raised an issue with the list owner re. The intel.com issues so
hopefully this should resolve itself shortly :)

I will add the track domains to the whitelist. Sadly there are sometimes
some false positives.

I was considering removing the track regexp as it seems to include many
false positives but will keep an eye on it for now

>
>

**Comment by mmotti** [comment]
Hi, me again :-)

Just wanted to let you know that I had raised the issue with **intel.com** a little while ago with the list maintainer and they quickly resolved it.

I have also more recently removed the tracking regexp as it was causing too many false positives, so these websites should no longer require any whitelisting.
