### ISSUE TITLE
please add new filters

### ISSUE THREAD

**Issue by YBS-PC** [mmotti/adguard-home-filters#2]
can you add (or make an additional file) these filters
https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/RussianFilter/sections/general_url.txt
https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_122_FanboysAnnoyances/filter.txt
https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_208_MalwareDomains/filter.txt
https://raw.githubusercontent.com/anudeepND/youtubeadsblacklist/master/domainlist.txt
https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt
https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/black.list
https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/MobileFilter/sections/adservers.txt
https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_207_AdblockWarningRemovalList/filter.txt
https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/EnglishFilter/sections/general_url.txt

and whitelists
https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/EnglishFilter/sections/whitelist.txt
https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/RussianFilter/sections/whitelist.txt

many thanks for your filter

**Comment by mmotti** [comment]
Hi,

Apologies - I do not plan to add additional filters at this time as I am trying to keep the false positives to a minimum.

The filters / hosts files that each individual uses are personal preference, so the solution really is for AdGuard Home to improve the processing of filter files.

There are two issues realted to this: 
https://github.com/AdguardTeam/AdGuardHome/issues/867
https://github.com/AdguardTeam/AdGuardHome/issues/892

I will consider adding the whitelist file back. I had this in a previous version, however removed it as I only really wanted whitelist domains that were valid for this filter list.

**Comment by YBS-PC** [comment]
thanks.  without this filter     https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/MobileFilter/sections/adservers.txt    my smartphones on the wifi network pass ads.

**Comment by mmotti** [comment]
I believe the mobile filter domains are included within [AdGuard Simplified domain names filter](https://filters.adtidy.org/extension/chromium/filters/15.txt)  which I have already added as a source :-)
