### ISSUE TITLE
why is the whitelist missing $important

### ISSUE THREAD

**Issue by YBS-PC** [mmotti/adguard-home-filters#3]
why is the whitelist missing $important ?

@@||a.adwolf.ru^ or @@||a.adwolf.ru^$important

**Comment by mmotti** [comment]
The reason for this is a mixture of a couple of things; being unclear on the priority flow with the use of the important option for blacklisting and whitelisting, and not wanting to impose on a users decision when it comes to whitelisting.

To expand a little on the latter, I didn't want to include whitelisted domains in my list which a user would be unable to overrule without excluding the list in its entirety.

If the priority system works as I think it does, it makes sense to use the important option sparingly, for the purpose of overruling conflicts
