### ISSUE TITLE
Google play updates blocked

### ISSUE THREAD

**Issue by jostyee** [mmotti/adguard-home-filters#5]
```regex
/^(.+[-_.])??xn--/
```

After applied the regex rules, all Android apps could'nt get updated any longer, have to remove this rule to make it work again.

**Comment by mmotti** [comment]
That's interesting - I haven't experienced this yet.

Where are you located or are you using a vpn in another country? I'm
scratching my head to think of why this might be an issue.

**Comment by jostyee** [comment]
It requires some urls like random strings for update files. Sorry I don't keep logs, next when I have outdated apps I'll post blocked records here.

**Comment by jostyee** [comment]
@mmotti Play requests url similar to `r2---sn-npobuxa-npoe6.xn--ngstr-lra8j.com` which matches the regex rule.

<img width="704" alt="Screenshot 2019-12-17 at 8 58 50 PM" src="https://user-images.githubusercontent.com/88564/70997441-11337600-2110-11ea-837f-82a97fc6b12f.png">
<img width="892" alt="Screenshot 2019-12-17 at 8 55 59 PM" src="https://user-images.githubusercontent.com/88564/70997450-15f82a00-2110-11ea-88ff-1cdee150846d.png">

**Comment by mmotti** [comment]
Thanks! I have tweaked the regexp to `^xn--` in the hopes that it will still catch a lot of these odd domains, but not cause conflicts with genuine cases like this.
