### ISSUE TITLE
gumtree.com blocked?

### ISSUE THREAD

**Issue by PedroLamas** [mmotti/adguard-home-filters#6]
Seems a bit odd to me to see www.gumtree.com appearing on the block list... as far as I know, this website is mostly for people to sell used stuff!

**Comment by mmotti** [comment]
Hmm.. Apologies for this. It would appear that one of the list maintainers
for the source lists have added it.

I will add a whitelist entry for it when I get a chance which should
overrule it.

Thanks for letting me know!

**Comment by mmotti** [comment]
Added to the whitelist. It will be reflected in the next sync.
