### ISSUE TITLE
Regex list

### ISSUE THREAD

**Issue by al-muftah** [mmotti/adguard-home-filters#7]
I have tried the regex list but does not work with Adguard Pro

**Comment by mmotti** [comment]
I will double check my setup to make sure but it has been fine on this end.

How have you added the entries?

**Comment by mmotti** [comment]
To add further:

You should add the following to your **DNS Blocklists**
https://raw.githubusercontent.com/mmotti/adguard-home-filters/master/regex.txt

If you try to access `ads.test.bbc.co.uk` you should find that it is blocked by `/^(.+[_.-])?ad[sxv]?[0-9]*[_.-]/`

Also make sure that you are using the latest version of AdGuard Home :-)

**Comment by al-muftah** [comment]
i am using Adguard Pro For iOS

**Comment by mmotti** [comment]
I'm not sure of the requirements for this. This repo is for Adguard Home
which is a standalone DNS solution :-)

**Comment by al-muftah** [comment]
Ok thx
