### ISSUE TITLE
track-and-trace.dhlparce.nl is blocked by regex

### ISSUE THREAD

**Issue by Melantrix** [mmotti/adguard-home-filters#9]
Hello,

This is a great blocklist, however i have one false positive. 
The domain track-and-trace.dhlparcel.nl is blocked by the rule Rule: /^track(ing)?[0-9]*[_.-]/ in the regex.txt. 

I'm not sure how to whitelist this without breaking the regex, but i thought i could let you know :)

**Comment by mmotti** [comment]
Hey!

Sadly there are some false positives every now and again when blanket blocking with regex.

You should be able to whitelist this particular entry with `@@||track-and-trace.dhlparcel.nl^` or if you'd like to whitelist the entire site `@@||dhlparcel.nl^`
@@||example.org^

**Comment by mmotti** [comment]
Oops didn't mean to close
